site_name: Architecture des ordinateurs
docs_dir: ../md
repo_url: https://github.com/jeremyfix/architecture
theme: 
  name: material
  language: fr
  features:
    - navigation.sections
    - navigation.instant
    - navigation.instant.progress
    - toc.follow
    - toc.integrate

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue-grey
      accent: blue-grey

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.critic
  - pymdownx.arithmatex:
      generic: true  
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_javascript:
  - https://code.jquery.com/jquery-3.7.1.min.js
  - ./js/seq_decode.js
  - ./js/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - css/extra.css

site_url: https://jeremyfix.github.io/Architecture/

plugins:
    - mkdocs-video
    - search
    - glightbox
    - awesome-nav 
    - privacy

copyright: >
  Copyright &copy; 2025 - Jérémy Fix –

